name: Bump Terraform CLI

description: Update the Terraform CLI version in a file to the latest available release.

inputs:
  file:
    description: Path to the file to update.
    required: true
  path:
    description: >
      yq expression targeting the value to update in the file: `.inputs.terraform-version.default`
      Mutually exclusive with match and replace.
    required: false
    default: ''
  match:
    description: Regex pattern matching the line to update in the file. Use with replace.
    required: false
    default: ''
  replace:
    description: Replacement line. Use {version} as the placeholder for the new version.
    required: false
    default: ''

outputs:
  version:
    description: The latest Terraform CLI version.
    value: ${{ steps.bump-terraform-cli.outputs.version }}
  changed:
    description: Whether the file was modified by this run.
    value: ${{ steps.bump-terraform-cli.outputs.changed }}
  file:
    description: Path to the file targeted by the bump.
    value: ${{ steps.bump-terraform-cli.outputs.file }}

runs:
  using: composite
  steps:
    - name: Bump Terraform CLI
      id: bump-terraform-cli
      run: ${{ github.action_path }}/src/bump_terraform_cli.sh
      shell: sh
      env:
        FILE: ${{ inputs.file }}
        YAML_PATH: ${{ inputs.path }}
        LINE_MATCH: ${{ inputs.match }}
        LINE_REPLACE: ${{ inputs.replace }}
